[package]
name = "day2"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[lib]
name = "aoc2023_day2"

[dependencies]
aoc2023-utils = { path = "../../utils" }
