[package]
name = "day1"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
aoc2023-utils = { path = "../../utils" }
lazy_static.workspace = true
